<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\IncomingEvents' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Controller\\IncomingEvents.php';

return $this->services['App\\Controller\\IncomingEvents'] = new \App\Controller\IncomingEvents();
