<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVBziwWd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVBziwWd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVBziwWd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVBziwWd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVBziwWd\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VBziwWd',
    'container.build_id' => '2cba764b',
    'container.build_time' => 1573105401,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVBziwWd');
