<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYJoEwwx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYJoEwwx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYJoEwwx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYJoEwwx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYJoEwwx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YJoEwwx',
    'container.build_id' => 'd9fe6dac',
    'container.build_time' => 1574964814,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYJoEwwx');
