<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYGelkZg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYGelkZg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYGelkZg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYGelkZg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYGelkZg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YGelkZg',
    'container.build_id' => 'aa27611a',
    'container.build_time' => 1573127403,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYGelkZg');
